
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: emqx-replicant-hpa
  namespace: mqtt
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: emqx-replicant
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
