
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: emqx-cluster-role
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: emqx-cluster-role-binding
roleRef:
  kind: ClusterRole
  name: emqx-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: mqtt
