apiVersion: v1
kind: Service
metadata:
  name: data-processing-service
  namespace: processing
spec:
  selector:
    app: data-processing
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080  # 외부에서 접근할 포트

