apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
  namespace: haproxy
spec:
  type: NodePort  # 또는 LoadBalancer
  selector:
    app: haproxy
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
    nodePort: 31234  # 외부에서 접근 시 포트
    
  - name: stats
    port: 8888
    targetPort: 8888
    nodePort: 31893
