apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: processing  # 필요 시 실제 네임스페이스로 변경
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: xxxxx
  AWS_SECRET_ACCESS_KEY: xxxxx
  AWS_REGION: ap-northeast-2

